### ISSUE TITLE
FlamingPy project not appearing

### ISSUE THREAD

**Issue by BestQuark** [unitaryfund/unitaryhackdev#90]
**Describe the bug**
Hi Unitaryfund team! I was checking the website and realized that the FlamingPy project does not appear on the main site. 

 **EDIT:** The project now appears, but the bounties don't appear.

**To Reproduce**
1. Go to [projects](https://unitaryhack.dev/projects/). 
2. FlamingPy section was not built completely.

**Expected behavior**

The bounties are not appearing.

**Screenshots**
Current online website: 

<img width="1665" alt="Screen Shot 2022-06-03 at 12 03 19 PM" src="https://user-images.githubusercontent.com/52287586/171903021-7870e5a7-5e8c-4659-a6eb-b8acd2d18f23.png">

**Comment by natestemen** [comment]
Sorry for the delay! We were having some problems with our github actions pipeline, that now seem to be resolved. I can see the bounties on the website now. If you're still experiencing problems let us know!
