### ISSUE TITLE
Uppercase text breaks links to projects on bounties page

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitaryhackdev#98]
The links to the projects on the bounties page introduced in #94 are broken. 
Because of the fact that the project titles are parsed with upper case letters, instead of all lowercase, the link does not work.
Example:
https://unitaryhack.dev/projects/NetKet (broken, obtained by clicking on NetKet from the [bounties](https://unitaryhack.dev/bounties/) page)
https://unitaryhack.dev/projects/netket (correct)

**Comment by mstechly** [comment]
On top of that, spaces in the name of the project also break them.
Example:
- https://unitaryhack.dev/projects/qiskit-ionq/ (works)
- https://unitaryhack.dev/projects/Qiskit%20IonQ (broken)
- https://unitaryhack.dev/projects/qiskit%20ionq (still broken, even after replacing uppercase letters)
